### PR TITLE
Restore support for external Python package platform dependencies

### PR DESCRIPTION
**Pull request by per1234**
## Background

Although Arduino boards platforms traditionally have bundled all dependencies, there are some cases where the user will need to use a preceding workflow [step](https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idsteps) to install external dependencies in the GitHub Actions [runner](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners) environment.

Since it is a "[composite action](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action)", this is feasible and was previously supported. However, support for Python package dependencies is more complicated due to the action script running in a Python virtual environment which isolates it from packages installed globally. The workaround for this was to use [the `--system-site-packages` flag](https://docs.python.org/3/library/venv.html#:~:text=message%20and%20exit-,%2D%2Dsystem%2Dsite%2Dpackages,-Give%20the%20virtual) in the [`venv`](https://docs.python.org/3/library/venv.html) invocation that created the action's Python virtual environment (https://github.com/arduino/compile-sketches/pull/15).

The previous approach to supporting user installed Python package dependencies of boards platforms introduced a requirement that the project Python version match the minor version series of the runner system Python. That requirement was violated when the workflow's runner was updated to `ubuntu-22.04` [which has system Python 3.10.x](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#user-content-language-and-runtime), whereas the action used 3.8.x. The breakage went unnoticed because the sole Python package platform dependency in real world usage, [**pyserial**](https://pyserial.readthedocs.io/en/latest/index.html), had been preinstalled in the runner's [Linux package manager "site-packages" folder](https://wiki.debian.org/Python#Deviations_from_upstream), which caused it to be installed in the action's virtual environment even though it would not have if depending on the user installation of the package as was previously the case.

## Problem

The previous approach to supporting user installed Python package dependencies of boards platforms introduced a requirement that the project Python version match the minor version series of the runner system Python. That requirement was violated when the workflow's runner was updated to `ubuntu-22.04` [which has system Python 3.10.x](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#user-content-language-and-runtime), whereas the action used 3.8.x. The breakage went unnoticed because the sole Python package platform dependency in real world usage, [**pyserial**](https://pyserial.readthedocs.io/en/latest/index.html), had been preinstalled in the runner's [Linux package manager "site-packages" folder](https://wiki.debian.org/Python#Deviations_from_upstream), which caused it to be installed in the action's virtual environment even though it would not have if depending on the user installation of the package as was previously the case.

In addition to the historical loss of support for arbitrary user installed Python packages, the support for packages that happened to be pre-installed on the runner was lost when a new virtual environment system was introduced (https://github.com/arduino/compile-sketches/pull/107).

## Solution

The obvious solution would have been to use the same "system-site-packages" configuration for [**Poetry**](https://python-poetry.org/) ([which does have support for it](https://python-poetry.org/docs/configuration/#virtualenvsoptionssystem-site-packages)). However, this was not possible because **Poetry** requires all packages to use [PEP 440](https://peps.python.org/pep-0440/)-compliant version numbers and the GitHub Actions runner contains a system installed Python package with a non-compliant version (https://github.com/python-poetry/poetry/issues/7343).

The usable solution is to use a path configuration file to [add the path](https://docs.python.org/3/library/site.html#index-2) of the system Python's "[user site-packages](https://peps.python.org/pep-0370/)" folder (where package dependencies installed via the workflow are located) to the module search paths used by the action's Python virtual environment.

This is actually superior to the "system-site-packages" in some ways:

- It avoids the chance of interference with the virtual environment through the unnecessary introduction of the global "site-packages" path into the module search paths along with the intended introduction of the "user site-packages" path.
- It allows any version of Python to be used to run the action, rather than being forced to use the same minor version series as the runner's system Python (which can be updated at any time and also depends on the [workflow configuration](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on))

## Legacy Workflow Support

The ESP32 boards platform expects the **pyserial** Python package to be preinstalled on Linux systems.

The situation is more complex when it comes to this important boards platform. The problem is that there is an established use pattern that should be supported to avoid breaking user workflows. The pattern is the use of a `pip install pyserial` command in the workflow to install the package ([e.g.](https://github.com/arduino-libraries/ArduinoIoTCloud/blob/1.11.0/.github/workflows/compile-examples.yml#L206)). That command correctly installs the package in the "user site-packages" folder when the job runs in [the `ubuntu-18.04` GitHub Actions runner](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources), as was the case when the use pattern was established. However, **pyserial** is installed in the Linux package manager "site-packages" folder of the Ubuntu GitHub Actions runner starting from `ubuntu-20.04` (most workflows run the **arduino/compile-sketches** job in the `ubuntu-latest` runner, which is currently `ubuntu-22.04`). This causes the established installation command to terminate without installing the package to the "user site-packages" folder:

```text
Requirement already satisfied: pyserial in /usr/lib/python3/dist-packages (3.5)
```

Now that only the user-installed packages from the "user site-packages" are added to the virtual environment, this would cause compilation for any ESP32 board to fail:

```text
ModuleNotFoundError: No module named 'serial'
```

The problem of the terminated **pyserial** installation does not occur if the user's installation command is configured as recommended in the newly added FAQ item on installing Python package dependencies of boards platforms.

Although the goal was always to provide a flexible system that would allow the user installation of any arbitrary platform dependency, rather than hardcoding specific dependencies in the action itself, unfortunately I have not been able to find any way to progress in the improvement of the action while also supporting the existing workflows that compile for ESP32 boards. So as a workaround I am reluctantly adding the **pyserial** package to the action's virtual environment.

This workaround will be reverted before the 2.0.0 release of the action so the **pyserial** installation command should be retained in workflows (even though it is no longer required), and occurrences of the historical `pip install pyserial` (or `pip3 install pyserial`) commands should be updated to the recommended form:

```text
pip install --ignore-installed --user pyserial
```

### CODE REVIEW

**Comment by aentinger** [comment]
>[which has system Python 3.10.x](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#user-content-language-and-runtime), whereas the action used 3.8.x

Time and time again this aspect of Python comes back to bite the unsuspecting user.

Great finding @per1234 and thanks for fixing this :bow:

**Comment by 2bndy5** [comment]
@per1234 Instead of using deadsnake's PPA (which takes a long time to install), you could use actions/setup-python to not affect the runner's PATH and use the action's [`python-path` output](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#python-path) to create the venv. I have not tested this idea though.

**Comment by per1234** [comment]
Thanks @2bndy5. I didn't do that at the time I migrated the action to the "composite" type because at that time the use of actions within composite actions were not supported. Since then GitHub added support for doing that and I have been meaning to take advantage of it ever since then.

I finally got around to it last week and it works just fine: https://github.com/arduino/compile-sketches/pull/105

**Comment by 2bndy5** [comment]
After I posted that, I saw your changes. They work well, and the compile-sketches runtime is much much better. 🚀

**Comment by 2bndy5** [comment]
BTW, the threads for #91 and #86 got locked because someone got "pushy" with their comments. I'm not sure if #86 is a problem anymore (and if #91 is needed anymore).

**Pull request merged**
